[FIX] stock_picking_batch: validate batch with done transfers
Validating a batch doesn't work if, for instance, all included pickings
are already done

To reproduce the issue:
1. In Settings, enable "Batch Pickings"
2. Create a batch transfer BT with one picking P
3. Confirm BT
4. Process P (not BT)
5. Mark BT as done

Error: The "Immediate Transfer" wizard is displayed while it shouldn't.
(Then if the user clicks on "Apply", nothing happens, the BT is still in
progress)

The wizard is displayed if the number of not done/cancelled picking is
equal to the number of not done/cancelled pickings that do not have any
done quantity (which is the case here, each is equal to `0`)

OPW-2727764
OPW-2726257

closes odoo/odoo#82228

Signed-off-by: Tiffany Chang <tic@odoo.com>